config/routes.rb
ScBattle::Application.routes.draw do
  get "vote/cast"

  get "battle/index"

  get "battle/show"

  get "battle/create"

  get "track/create"

  root :to => "home#index"
  get "home/index"
  
  match '/you',           :to => 'welcome#show',    :as => :you
  match '/you/update',    :to => 'welcome#update',  :as => :you_update
  
  match '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  match '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  match '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  match '/track/create', :to => 'track#create', :as => :track_create
  match '/vote/cast', :to => 'vote#cast', :as => :vote_cast

  match ':controller(/:action(/:id(.:format)))'
end

app/models/battle.rb
class Battle < ActiveRecord::Base
  has_many :tracks
  has_many :users, :through => :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user
  belongs_to :battle
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tracks
  has_many :battles, :through => :tracks

  def self.soundcloud_client(options={})
    options = {
      :client_id     => APP_CONFIG['SOUNDCLOUD_KEY'],
      :client_secret => APP_CONFIG['SOUNDCLOUD_SECRET'],
    }.merge(options)

    Soundcloud.new(options)
  end

  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)

    client = self.class.soundcloud_client(options)

    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end
    client
  end
  def voted_for?(track_id)
    Track.find(track_id).votes.find(:first, :conditions => {:user_id => self[:id]}) ? true : false
  end
  def is_contestant?(battle_id)
    Battle.find(battle_id).users.find(:first, :conditions => {:id => self[:id]}) ? true : false
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :track
  validates_uniqueness_of :user_id, :scope => :battle_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login_from_session
  def logged_in?
    !!current_sc_user
  end
  
  def current_sc_user
    @current_sc_user
  end
  
  def login_as(user)
    @current_sc_user = user
    session[:current_sc_user_id] = user.try(:id)
  end
  
  def login_from_session
    @current_sc_user = User.find_by_id(session[:current_sc_user_id])
  end
  
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find_by_id(params[:id])
  end

  def create
    @battle = Battle.new()
    @battle.save
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # raise request.env["omniauth.auth"].to_yaml
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"].to_s) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def connect
    redirect_to soundcloud_client.authorize_url(:display => "popup")
  end

  def connected
    if params[:error].nil?
      soundcloud_client.exchange_token(:code => params[:code])
      me = soundcloud_client.get("/me")

      login_as User.find_or_create_by_soundcloud_uid({
        :soundcloud_uid  => me.id,
        :soundcloud_username => me.username
      })

      current_sc_user.update_attributes!({
        :soundcloud_access_token  => soundcloud_client.access_token,
        :soundcloud_refresh_token => soundcloud_client.refresh_token,
        :soundcloud_expires_at    => soundcloud_client.expires_at,
      })
    end
    # render :layout => false
    redirect_to root_path
    # render :text => "me is: #{me}"
  end

  def disconnect
    login_as nil
    redirect_to root_path
  end
  
private

  def soundcloud_client
    return @soundcloud_client if @soundcloud_client
    @soundcloud_client = User.soundcloud_client(:redirect_uri  => soundcloud_connected_url)
  end


end

app/controllers/track_controller.rb
class TrackController < ApplicationController
  def create
    @battle = Battle.find_by_id(params[:battle_id])
    @sondcloud_track = current_sc_user.soundcloud_client.get("/me/tracks/#{params[:soundcloud_track_id]}")
    @track = @battle.tracks.create(
      :user_id => current_sc_user[:id],
      :soundcloud_track_id => params[:soundcloud_track_id],
      :title => @sondcloud_track.title,
      :permalink => @sondcloud_track.permalink,
      :permalink_url => @sondcloud_track.permalink_url
    )
    if @track.save
      redirect_to "/battle/show/#{params[:battle_id]}"
    else
      # could not submit track
    end
  end
  def show
    @tracks = @current_sc_user.tracks
  end
  def new
    @battle_id = params[:id] #the battle the track will be submitted to
    @tracks = current_sc_user.soundcloud_client.get("/me/tracks", :limit => 5)
  end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def cast
    # check if already voted on track in this battle
    @vote = Vote.find(:first, :conditions => [
      "user_id = #{current_sc_user[:id]} AND battle_id = #{params[:battle_id]}"
    ])
    @soundcloud_track_id = Track.find(params[:track_id]).soundcloud_track_id
    if @vote.nil?
      # create new vote
      @vote = Vote.new(
        :track_id => params[:track_id],
        :soundcloud_track_id => @soundcloud_track_id,
        :user_id => current_sc_user[:id],
        :battle_id => params[:battle_id]
      )
      if @vote.save
        redirect_to "/battle/show/#{params[:battle_id]}"
      end
    else
      # update exisitng vote?
      if(@vote.track_id != params[:track_id])
        @vote.track_id = params[:track_id]
        @vote.soundcloud_track_id = @soundcloud_track_id
        if @vote.save
          redirect_to "/battle/show/#{params[:battle_id]}"
        end
      else
        logger.debug "You already voted for this track."
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
    @tracks = current_sc_user.soundcloud_client.get("/me/tracks", :limit => 5)
    @me     = current_sc_user.soundcloud_client.get("/me")
  end

  def update
    res = current_sc_user.soundcloud_client.put("/me", :user => {:description => params[:description]})
    redirect_to :action => :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_sc_user
    @current_sc_user
  end
  
  def logged_in?
    !!current_sc_user
  end
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/battle/create.html.erb
<h1>Battle#create</h1>
<p>Created battle <%= @battle.id %></p>

app/views/battle/index.html.erb
<h1>Battle#index</h1>

<div class="battles">
  <b>All Battles</b>
  <ul>
    <% @battles.each do |battle| %>
      <li><%= link_to "battle id: #{battle.id}", "/battle/show/#{battle.id}"%></li>
    <% end %>
  </ul>
</div>

app/views/battle/show.html.erb
<h1>Battle#show</h1>
<p>Battle id: <%= @battle.id %></p>

<div id="battle-tracks">
</div>

<% if logged_in? && !current_sc_user.is_contestant?(@battle.id)  %>
	<%= link_to "Join this battle", "/track/new/#{@battle.id}"%>
<% end %>

<script type="text/javascript">

	<% @battle.tracks.each do |track| %>

		var battle_id = '<%=@battle.id%>'
		var track_id = '<%=track.id%>'
		var title = '<%=track.title%>'
		var permalink_url = '<%=track.permalink_url%>'
		var votes = '<%=track.votes.size.to_s%>'
		var votedFor = '<%= !!logged_in? && current_sc_user.voted_for?(track.id) %>'
		var newtrack = new Track(battle_id, track_id, title, permalink_url, votes, votedFor, $("#battle-tracks"));
		console.log("newtrack ", newtrack);
		console.log("newtrack ", newtrack.votes);
	<% end %>

</script>

app/views/home/index.html.erb
<h1>Sound Cloud Battle <%- if RAILS_ENV == "development" -%>(dev)<%- end -%></h1>
<p>A Battle Arena for Sound Clouders</p>

<div class="connect-with-soundcloud <%= "connected" if logged_in? %>">
  <%= link_to "Connect With SoundCloud",    soundcloud_connect_path, :class => "connect" %>
  <%= link_to "Disconnect From SoundCloud", soundcloud_disconnect_path, :class => "disconnect" %>
  <span class="current-user">
    You are logged in as:
    <span class="username"><%= current_sc_user.soundcloud_username if logged_in? %></span>
  </span>
</div>

<div class="visible-when-logged-in <%= "hidden" unless logged_in? %>"">
  <%= link_to "Check out your profile infos", you_path %>

app/views/home/show.html.erb
<!-- what goes here -->

<div class="infos">
  <div class="details">
    <b>Your SoundCloud User Infos:</b>
    <ul>
      <li>Username: <%= @me.username %></li>
      <li>Fullname: <%= @me.full_name %></li>
      <li>Location: <%= @me.city %>, <%= @me.country %></li>
    </ul>
  </div>
  <%= image_tag(@me.avatar_url, :class => "avatar") %>
  
</div>

<div class="description">
  <% form_tag you_update_path, :method => "post" do %>
    <b>Description:</b>
    <textarea name="description"><%= @me.description %></textarea>
    <input type="submit" value="update" />
    <span class="warning">this will change your SoundCloud profile description!</span>
  <% end %>
</div>

<div class="tracks">
  <b>Your 5 latest tracks</b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= link_to track.title, track.permalink_url %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScBattle</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/track/create.html.erb
<h1>Track#create</h1>

<p>You submitted the track <%= @track.title %></p>

<p><%= link_to "See your submitted tracks", "/track/show" %></p>

app/views/track/new.html.erb
<div class="tracks">
  <b>Submit a track to enter Battle: <%= @battle_id %></b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= link_to track.title, "/track/create?soundcloud_track_id=#{track.id}&battle_id=#{@battle_id}" %></li>
    <% end %>
  </ul>
</div>

app/views/track/show.html.erb
<h1>Track#show</h1>

<div class="tracks">
  <b>Your submitted tracks</b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= track.title %></li>
	  <% end %>
  </ul>
</div>

app/views/vote/cast.html.erb
<h1>Vote#cast</h1>
<p>Find me in app/views/vote/cast.html.erb</p>

app/views/welcome/show.html.erb
<div class="infos">
  <div class="details">
    <b>Your SoundCloud User Infos:</b>
    <ul>
      <li>Username: <%= @me.username %></li>
      <li>Fullname: <%= @me.full_name %></li>
      <li>Location: <%= @me.city %>, <%= @me.country %></li>
    </ul>
  </div>
  <%= image_tag(@me.avatar_url, :class => "avatar") %>
  
</div>

<div class="description">
  <% form_tag you_update_path, :method => "post" do %>
    <b>Description:</b>
    <textarea name="description"><%= @me.description %></textarea>
    <input type="submit" value="update" />
    <span class="warning">this will change your SoundCloud profile description!</span>
  <% end %>
</div>

<div class="tracks">
  <b>Your 5 latest tracks</b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= link_to track.title, "track/create?soundcloud_track_id=#{track.id}&title=#{CGI.escape(track.title)}" %><%= track.to_yaml %></li>
    <% end %>
  </ul>
</div>